---
- name: Disable and stop service
  service: >
    name=php-fpm
    enabled=no
    state=stopped

- name: Remove packages
  yum:
    pkg={{item}}
    state=absent
  with_items:
    - php
    - php-cli
    - php-mysql
    - php-mbstring
    - php-gd
    - php-fpm

- name: Remove additional packages for PHP
  yum:
    pkg={{item}}
    state=absent
  with_items:
    - ImageMagick
    - bind-utils

- name: Remove link to ImageMagick commands
  file:
    path=/usr/local/bin/{{item}}
    state=absent
  with_items:
    - identify
    - convert

- name: Remove config php.ini
  file:
    path=/etc/php.ini
    state=absent

- name: Remove config main php-fpm
  file:
    path=/etc/php-fpm.conf
    state=absent

- name: Remove config www php-fpm pool
  file:
    path=/etc/php-fpm.d/www.conf
    state=absent

- name: Remove log
  file:
    path=/var/log/php-fpm/
    state=absent

