---
- name: Copy config php.ini
  copy: >
    src=php.ini
    dest=/etc/php.ini
    owner: root
    group: root
    mode: 0644

- name: Copy config main php-fpm
  copy: >
    src=php-fpm.conf
    dest=/etc/php-fpm.conf
    owner: root
    group: root
    mode: 0644

- name: Copy config www php-fpm pool
  template: >
    src=php-fpm.d/www.conf.j2
    dest=/etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644

## Create link to ImageMagick commands
- name:  Create link to ImageMagick commands
  shell: ln -s /usr/bin/identify /usr/local/bin/identify && ln -s /usr/bin/convert /usr/local/bin/convert