---
- name: Remove Epel, Remi, Zabbix repo
  yum:
    name={{item}}
    state=absent
  with_items:
    - epel-release
    - remi-relese
    - zabbix-release

- name: Remove yum cache
  command: yum clean all

