---
- name: Install EPEL repository for CentOS 6
  yum: name=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: Install EPEL repository for CentOS 7
  yum: name=https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm state=present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
