---
- name: Install EPEL repository for CentOS 6
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: Install EPEL repository for CentOS 7
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
