---
- name: Install REMI repository for CentOS 6
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") and (php_version == 5.4 or php_version == 5.5 or php_version == 5.6)

- name: Install REMI repository for CentOS 7
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") and (php_version == 5.5 or php_version == 5.6)