---
- name: Install Zabbix repository for CentOS 6
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Install Zabbix repository for CentOS 7
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"