---
- name: Disable and stop service
  service:
    name=nginx
    enabled=no
    state=stopped

- name: Remove packages
  yum:
    pkg={{item}}
    state=absent
  with_items:
    - nginx

- name: Remove repository
  yum:
    name=nginx-release
    state=absent

- name: Remove config
  file:
    path=/etc/nginx/
    state=absent

- name: Remove www directory
  file:
    path=/home/dev/www/{{ prj_host }}/www/
    state=absent

- name: Remove logrotate
  file:
    path=/etc/logrotate.d/{{item}}
    state=absent
  with_items:
    - www.conf
    - dev.conf

