---
- name: Nginx | Copy wp config
  template: >
    src=hosts/virtualhost-wp.conf.j2
    dest=/etc/nginx/hosts/{{ prj_host }}.conf

- name: Nginx | Secure wp site
  copy: >
    src=includes
    dest=/etc/nginx/
    owner=root
    group=root
    mode=0644

- name: Nginx | Copy wp ssl config
  template: >
    src=hosts/virtualhost-wp-ssl.conf.j2
    dest=/etc/nginx/hosts/{{ prj_host }}-ssl.conf
  when: prj_ssl

