---
- name: Copy v5 config
  template: >
    src=hosts/virtualhost-v5.conf.j2
    dest=/etc/nginx/hosts/{{ prj_host }}.conf

- name: Copy v5 ssl config
  template: >
    src=hosts/virtualhost-v5-ssl.conf.j2
    dest=/etc/nginx/hosts/{{ prj_host }}-ssl.conf
  when: prj_ssl