---
- include: packages.yml
  tags: setup,nginx

- include: config.yml
  tags: setup,nginx

- include: config-v5.yml
  tags: setup,nginx
  when: prj_type == 'v5'

- include: config-wp.yml
  tags: setup,nginx
  when: prj_type == 'wp'

- include: ssl.yml
  tags: setup,nginx,ssl

- include: setup-main-page.yml
  tags: setup,nginx,deploy

- include: service.yml
  tags: setup,nginx,service

- include: logrotate.yml
  tags: setup,nginx,logrotate

- include: clean.yml
  tags: clean

