---
- include: packages.yml tags=setup,hotfix,nginx

- include: config.yml tags=setup,hotfix,nginx

- include: config-v5.yml tags=setup,hotfix,nginx
  when: prj_type == 'v5'

- include: config-wp.yml tags=setup,hotfix,nginx
  when: prj_type == 'wp'

- include: ssl.yml tags=setup,hotfix,nginx,ssl

- include: setup-main-page.yml tags=setup,hotfix,nginx,deploy

- include: service.yml tags=setup,hotfix,nginx

- include: logrotate.yml tags=setup,hotfix,nginx,logrotate