---
- name: Nginx | Copy ssl cert
  copy: >
    src=ssl/{{ prj_host }}.crt
    dest=/etc/nginx/ssl/
    owner=nginx
    group=www
    mode=0400
  when: prj_ssl

- name: Nginx | Copy ssl private key
  copy: >
    src=ssl/{{ prj_host }}.key
    dest=/etc/nginx/ssl/{{ prj_host }}.key
    owner=nginx
    group=www
    mode=0400
  when: prj_ssl