---
- name: Remove project user
  user: 
    name={{ prj_user }}
    remove

- name: Remove project group
  group:
    name={{ prj_group }}
    remove

- name: Remove project user's home
  file: >
    path=/home/{{ prj_user }}
    state=absent

