---
- name: MySQL | Copy config
  copy: >
    src=my.cnf
    dest=/etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: MySQL | Configure log
  file: >
    path=/var/log/mysql
    owner=mysql
    group=mysql
    mode=0770
    state=directory
