---
- name: Enable and start service for CentOS 6
  service: >
    name=mysqld
    enabled=yes
    state=restarted
  when: ansible_distribution_major_version == "6"

- name: Enable and start service for CentOS 7
  service: >
    name=mariadb
    enabled=yes
    state=restarted
  when: ansible_distribution_major_version == "7"
