---
- name: Install OpenSSH Server
  yum: >
    pkg={{item}}
    state=latest
  with_items:
    - openssh-server

- name: Copy OpenSSH Server Config
  copy: src=sshd_config dest=/etc/ssh/sshd_config

- name: Start OpenSSH Server
  service: >
    name=sshd
    state=restarted
    enabled=yes